import test from 'node:test';
import assert from 'node:assert/strict';

test('bridge buffers pre-initialize state, deduplicates versions, resets per match and bounds pending work', async () => {
  const windowStub = new EventTarget();
  windowStub.parent = windowStub;
  globalThis.window = windowStub;
  const { PlayweftBridge } = await import('../src/playweft-client.js');
  const bridge = new PlayweftBridge();
  const requests = [];
  const fakePort = { postMessage: (m) => requests.push(m), start() {}, close() {} };
  const snapshots = [];
  bridge.addEventListener('state', (event) => snapshots.push(event.detail));
  bridge.onWindowMessage({ source: {}, data: { type: 'playweft:bridge', version: 1 }, ports: [fakePort] });
  assert.equal(bridge.port, null);
  bridge.onWindowMessage({ source: windowStub, data: { type: 'playweft:bridge', version: 1 }, ports: [fakePort] });
  assert.equal(requests[0].method, 'game.initialize');
  const snapshot = (version, matchId = 'm1') => ({ jsonrpc: '2.0', method: 'game.state', params: { state: { round: 1 }, version, matchId } });
  bridge.receive(snapshot(2));
  assert.equal(snapshots.length, 0);
  bridge.receive({ jsonrpc: '2.0', id: requests[0].id, result: { mode: 'room', playerId: 'p1' } });
  await Promise.resolve();
  assert.equal(snapshots.length, 1);
  bridge.receive(snapshot(2)); bridge.receive(snapshot(1));
  assert.equal(snapshots.length, 1);
  bridge.receive(snapshot(3)); bridge.receive(snapshot(0, 'm2'));
  assert.equal(snapshots.length, 3);
  const action = bridge.action({ type: 'turn', direction: 1, round: 1 });
  const request = requests.at(-1);
  assert.equal(request.method, 'room.action');
  assert.deepEqual(request.params.action, { type: 'turn', direction: 1, round: 1 });
  bridge.receive({ jsonrpc: '2.0', id: request.id, result: { accepted: true } });
  assert.deepEqual(await action, { accepted: true });
  const outstanding = Array.from({ length: 8 }, () => bridge.call('room.action', {}).catch((e) => e.message));
  await assert.rejects(bridge.call('room.action', {}), /Too many pending/);
  bridge.close();
  assert.equal(bridge.pending.size, 0);
  await Promise.all(outstanding);
  delete globalThis.window;
});
